#!/usr/bin/env python3
"""Write docs/MANIFEST.md: which script produces each data file, figure, table and number.

    python src/build_manifest.py

The manifest is generated by reading the scripts themselves (their `write_csv`, `read_csv`,
`save`, `read`, `md_table` and `put` calls), so it cannot drift from the code the way a
hand-written inventory does.
"""
import ast
import os
import re
import sys

SRC = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SRC)
EXP = os.path.join(SRC, "experiments")
FIG = os.path.join(SRC, "figures")
OUT = os.path.join(ROOT, "docs", "MANIFEST.md")


def _strings(node):
    return [n.value for n in ast.walk(node) if isinstance(n, ast.Constant) and isinstance(n.value, str)]


def _calls(tree, name):
    """All calls to `name` (or `obj.name`), as lists of their string arguments."""
    out = []
    for n in ast.walk(tree):
        if not isinstance(n, ast.Call):
            continue
        f = n.func
        fname = f.attr if isinstance(f, ast.Attribute) else getattr(f, "id", None)
        if fname == name:
            out.append([a.value for a in n.args
                        if isinstance(a, ast.Constant) and isinstance(a.value, str)])
    return out


def experiments():
    rows = []
    for f in sorted(os.listdir(EXP)):
        if not re.match(r"e\d\d.*\.py$", f):
            continue
        tree = ast.parse(open(os.path.join(EXP, f)).read())
        outs = [a[0] for a in _calls(tree, "write_csv") if a]
        outs += sorted(set(re.findall(r'"([A-Za-z0-9_]+\.npz)"', open(os.path.join(EXP, f)).read())))
        doc = (ast.get_docstring(tree) or "").split("\n")[0]
        rows.append((f, doc, outs))
    return rows


def figures():
    rows = []
    for f in sorted(os.listdir(FIG)):
        if not f.startswith("fig") or not f.endswith(".py"):
            continue
        src = open(os.path.join(FIG, f)).read()
        tree = ast.parse(src)
        ins = sorted({s for c in _calls(tree, "read_csv") for s in c if s.endswith(".csv")} |
                     {s for c in _calls(tree, "load") for s in c if s.endswith(".npz")})
        outs = [a[-1] for a in _calls(tree, "save") if a]
        doc = (ast.get_docstring(tree) or "").split("\n")[0]
        rows.append((f, doc, ins, outs))
    return rows


def tables_and_numbers():
    """For each section of build_tables.py: inputs, generated tables, and number keys."""
    tree = ast.parse(open(os.path.join(SRC, "build_tables.py")).read())
    rows = []
    for fn in [n for n in tree.body if isinstance(n, ast.FunctionDef)]:
        ins = sorted({a[0] for a in _calls(fn, "read") if a and a[0].endswith(".csv")})
        tabs = sorted({a[1] for a in _calls(fn, "md_table") if len(a) > 1})
        keys = [a[0] for a in _calls(fn, "put") if a]
        dyn = sum(1 for n in ast.walk(fn) if isinstance(n, ast.Call)
                  and getattr(n.func, "id", None) == "put"
                  and n.args and isinstance(n.args[0], ast.JoinedStr))
        if not (ins or tabs or keys or dyn):
            continue
        rows.append((fn.name, ins, tabs, len(keys), dyn))
    return rows


def main():
    L = []
    L.append("<!-- Generated by src/build_manifest.py. Do not edit. -->")
    L.append("# Manifest: every result, figure, table and number and the script that makes it\n")
    L.append("`python run_all.py` runs the whole chain. Each experiment also writes a `.meta.json` "
             "next to its CSV with the parameter set actually used.\n")

    L.append("## Experiments → data\n")
    L.append("| Script | What it runs | Output in `results/data/` |")
    L.append("|---|---|---|")
    for f, doc, outs in experiments():
        L.append(f"| `src/experiments/{f}` | {doc} | {', '.join('`'+o+'`' for o in outs) or '–'} |")

    L.append("\n## Data → figures\n")
    L.append("| Figure | Script | Reads |")
    L.append("|---|---|---|")
    for f, doc, ins, outs in figures():
        L.append(f"| `results/figures/{outs[0] if outs else '?'}` | `src/figures/{f}` | "
                 f"{', '.join('`'+i+'`' for i in ins) or '–'} |")

    L.append("\n## Data → tables and quoted numbers\n")
    L.append("Every `{{key}}` in the manuscript sources is resolved from "
             "`manuscript/generated/numbers.json`; the build fails on any key with no value.\n")
    L.append("| Section of `src/build_tables.py` | Reads | Generates | Numbers |")
    L.append("|---|---|---|---|")
    for name, ins, tabs, nkeys, dyn in tables_and_numbers():
        n = f"{nkeys} fixed" + (f" + {dyn} generated" if dyn else "")
        L.append(f"| `{name}()` | {', '.join('`'+i+'`' for i in ins) or '–'} | "
                 f"{', '.join('`'+t+'`' for t in tabs) or '–'} | {n} |")

    L.append("\n## Documents\n")
    L.append("| Output | Built by | From |")
    L.append("|---|---|---|")
    L.append("| `manuscript/ephaptic_crosstalk_manuscript.{md,docx,pdf}` | "
             "`manuscript/build_manuscript.py` | `manuscript/sections/*.md` + `numbers.json` |")
    L.append("| `manuscript/supplementary_information.{md,docx,pdf}` | "
             "`manuscript/build_manuscript.py` | `manuscript/supplement/*.md` + `numbers.json` |")
    L.append("| `README.md`, `docs/RESPONSE_TO_REVIEWERS.md`, `manuscript/cover_letter.md` | "
             "`manuscript/build_manuscript.py` | `docs/templates/*.tmpl.md` + `numbers.json` |")
    L.append("| `submission/` | `src/build_package.py` | the files above |")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(L) + "\n")
    print("  wrote", os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
